#ifndef TEST14_LIBRARY_GLOBAL_H
#define TEST14_LIBRARY_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TEST14_LIBRARY_LIBRARY)
#  define TEST14_LIBRARYSHARED_EXPORT Q_DECL_EXPORT
#else
#  define TEST14_LIBRARYSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // TEST14_LIBRARY_GLOBAL_H
